version: '3'

services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/tblanco/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/tblanco/data/mariadb'

networks:
  inception:
    driver: bridge
