version: '3'

services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception

networks:
  inception:
    driver: bridge

