version: '3'

services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    ports:
      - 443:80
    networks:
      - inception

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    build: 
      context: requirements/wordpress
    container_name: wordpress

networks:
  inception:
    driver: bridge
